### ISSUE TITLE
In population off datalad-usage-dashboard take only datasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#105]
i.e. only those which have ` "dataset": true,`. No point of looking at those with RUN records etc, and there is growing number of them while on the codespelling quest using `datalad run` all the time ;)

**Comment by candleindark** [comment]
If I understand you correctly, I believe the current behavior is already what you want.

https://github.com/datalad/datalad-registry/blob/master/tools/populate.py#L92-L97

Currently, the population script only takes those on the dashboard which are marked active and as a dataset.

**Comment by yarikoptic** [comment]
ha -- cool, indeed ;)
