### ISSUE TITLE
extract/store metadata for dandisets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#129]
- [ ] needs metadata extractor to be provided . This datalad extension already depends on metalad, I don't think there is sense in developing dedicated dandi datalad extension ATM
   - all DataLad dandisets have metadata provided in  (example on randomly chosen 000402) [dandiset.yaml](https://github.com/dandisets/000402/blob/draft/dandiset.yaml) for dataset level, and then [.dandi/assets.json](https://github.com/dandisets/000402/blob/draft/.dandi/assets.json) for each asset.  So for starters it is just a matter of loading them all up
- [ ] identify dandisets by presence of `dandiset.yaml` in the top directory

**Comment by candleindark** [comment]
I have the following questions/statements to be confirmed/answered.

1. A Dandiset is a Datalad dataset. [True/False]
2. Assuming the last statement is True. A proper Dandiset contains a `dandiset.yaml` directly under. [True/False]
3. Does every Dandiset contain a `.dandi/assets.json`?
4. Assuming 1 and 2 are both true. For the extraction of metadata from a Dandiset, you want to load the data from the `dandiset.yaml` and `.dandi/assets.json` (if `.dandi/assets.json` exists`) and save the loaded data to the database in JSON format. [True/False]
5. Assuming 4 is true. How do you want to combine the loaded data from both `dandiset.yaml` and `.dandi/assets.json`? Do you want to put the two pieces of data under different keys? If yes, what keys?
6. You want datalad-registry to extract the aforementioned metadata from a Dandiset directly without going through the `dataset metalad` extension, which does not support such extraction at this point. [True/False]

**Comment by candleindark** [comment]
@yarikoptic Is it possible for the "dandiset.yaml" file, as a document stream, to contain more than one document?

**Comment by yarikoptic** [comment]
that should not happen. It would be ok to error out if it does

**Comment by candleindark** [comment]
This issue has been closed by #257.
