### ISSUE TITLE
Why last-update 	 2023-02-23T02:00:34+0000 ?  Adjust update strategy

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#134]
I highly doubt that there were no changes to any of the repositories since then.  Don't we run some cron job which tests if there are updates to already known datasets? obviously we might be not running enough of updates but we should get some and we should do them by looking first at the least recently updated -- i.e. with the oldest `info_ts`, and thus result in them being updated even if there is no actual updates from the remote.

**Comment by candleindark** [comment]
There is a cron job running, but I don't think the update logic is right as mentioned in https://github.com/datalad/datalad-registry/issues/136. I will put in some changes to make update working starting with re-organizing the local cache as discussed in https://github.com/datalad/datalad-registry/issues/125.

**Comment by candleindark** [comment]
PR #238 closes this issue as well.

**Comment by yarikoptic** [comment]
if it does -- add `Closes #238` in the description of that PR and the issue would be closed when that PR is merged
