### ISSUE TITLE
Why git objects size is 0 for some repos where it is clearly not

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#135]
e.g. I know that https://github.com/dandi/dandi-api-webshots.git is **huge** in  terms of `.git/objects` but it is listed as `0` in .git/objects size. Why?

**Comment by candleindark** [comment]
The statement that retrieve the size in the current code is https://github.com/datalad/datalad-registry/blob/67f7f34877f87c9ba89634ab5644c70eae4ea044/datalad_registry/tasks.py#L81.

I tried to replicate the problem with the following piece of code:

```python
from tempfile import TemporaryDirectory
from pprint import pprint

from datalad import api as dl


source = "https://github.com/dandi/dandi-api-webshots.git"

with TemporaryDirectory() as tmp_dir:
    ds = dl.clone(source, path=tmp_dir)
    count_objects = ds.repo.count_objects

    print("count_objects: ")
    pprint(count_objects)
```

The result of running this code is

```
[INFO] Attempting a clone into /var/folders/27/12wj99x53kn5v0mld3xs03980000gp/T/tmpt7bnfjjf 
[INFO] Attempting to clone from https://github.com/dandi/dandi-api-webshots.git to /var/folders/27/12wj99x53kn5v0mld3xs03980000gp/T/tmpt7bnfjjf 
[INFO] Start enumerating objects 
[INFO] Start counting objects 
[INFO] Start compressing objects 
[INFO] Start receiving objects 
[INFO] Start resolving deltas 
[INFO] Completed clone attempts for Dataset(/var/folders/27/12wj99x53kn5v0mld3xs03980000gp/T/tmpt7bnfjjf) 
install(ok): /var/folders/27/12wj99x53kn5v0mld3xs03980000gp/T/tmpt7bnfjjf (dataset)
count_objects: 
{'count': 0,
 'garbage': 0,
 'in-pack': 381473,
 'packs': 1,
 'prune-packable': 0,
 'size': 0,
 'size-garbage': 0,
 'size-pack': 2784464}
```

The result looks the same as the one produced by Datalad-registry. The `.git/objects` size is 0. It doesn't seem to be by caused the URL population process of Datalad-registry. 

Is `ds.repo.count_objects["size"]` the right statement to obtain the size of `.git/objects`?

**Comment by yarikoptic** [comment]
I think we should just add up `size` and `size-pack` as I was suggesting originally in https://github.com/datalad/datalad-registry/issues/40#issuecomment-904924614 .
