### ISSUE TITLE
make a script to populate/trigger update for repos from gin

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#157]
There is https://gin.g-node.org/explore/repos with bunch of repos, some of which are datalad datasets, and most of them are git-annex repos.  note: some of them are quite large in `.git/objects` since not configured correctly.   I believe that there is an API we could use to write such a little script . some exploration of it was done https://github.com/datalad/datalad-usage-dashboard/issues/15 for the search purpose but since it is not "good enough" here we can probably just register ALL of them and be done ;-)

**Comment by candleindark** [comment]
Do you mean to write a script to register all the datasets at https://gin.g-node.org/explore/repos to datalad-registry?

**Comment by yarikoptic** [comment]
yes, but it seems that API is down https://github.com/G-Node/gin-cli/issues/125#issuecomment-1517191074

**Comment by candleindark** [comment]
Please note that any registering of the datasets should be done on a weekend as discussed in https://github.com/G-Node/gin-cli/issues/125#issuecomment-1518362740.

**Comment by yarikoptic** [comment]
Sample repos to try on first from gin:
- https://gin.g-node.org/CIMeC/TMS-EEG_brain_connectivity_BIDS -- it is a BIDS dataset but not DataLad dataset (thus #160 should be done first)

**Comment by yarikoptic** [comment]
ok. I think we better channel those through the dashboard first, not necessarily looking for datasets. Then we could just rely on #271 to keep it updated.  Hence let's consider replaced by https://github.com/datalad/datalad-usage-dashboard/issues/15
