### ISSUE TITLE
Make sure that the code works with pure git/git-annex repos

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#160]
May be it is already tested that the whole thing works even if there is no `.datalad/config` which defines UUID for datalad dataset.

Test should test on at least two regular git and/or git-annex repos, and ensure that DB does get two separate entries for them and we can query based on URL.

**Comment by yarikoptic** [comment]
FWIW, I added two repos from gin.g-node and their records seems to remain empty http://localhost:5000/overview/?filter=gin.g-node&sort=update-desc

**Comment by candleindark** [comment]
The two added records by @yarikoptic were https://gin.g-node.org/CIMeC/TMS-EEG_brain_connectivity_BIDS and https://gin.g-node.org/gaalzs/checkerboard_vMMN_2023.

Ensure those work under the V2 API / new dataset URL processing.

**Comment by yarikoptic** [comment]
where are we on this one @candleindark - may be it could be closed already?

**Comment by yarikoptic** [comment]
please POST for those two urls and we will see/make sure that it is all good

**Comment by candleindark** [comment]
Those URLs have been posted to the running instance of Datalad-Registry. If those looks good to you, @yarikoptic, I think we can close this issue. There is a remaining problem in metadata extraction relating to this one. Issue #272 has been filed to handle it.
