### ISSUE TITLE
Add to /api/v2/dataset-urls options to also include metadata in return

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#176]
We might want to include specific extractors metadata

- `return_metadata: str`: "", "references" (`{"metalad_core": "http://localhost:5000/api/v2/url-metadata/54"}, "content" (`{"metalad_core": {...}`)

based on the value of `return_metadata` the result would populate `"metadata"` field in the return.  so with `return_metadata="references"` you get records sufficient to display what we display now in web UI. Good point to try jqtables (as on datasets.datalad.org)

**Comment by candleindark** [comment]
@yarikoptic In this design, we will have an issue if we, in the future, decide to return multiple versions of metadata extracted by the same extractor of the same dataset (or we decide to keep multiple versions of metadata extracted by the same extractor of the same dataset). If it is possible that we are going make such a decision, I think we should return the metadata of a dataset at a URL in a list of objects. In the case of "content", each of these object represents a version of metadata by a particular extractor. In the case of "references", each of these object represents a reference to such a version of metadata.
