### ISSUE TITLE
Improvement: Update the `URL` database model

### ISSUE THREAD

**Issue by candleindark** [datalad/datalad-registry#186]
Do the following to improve the definition of the `URL` database model.

- [x] 1. Rename it. A good choice to rename to is `DatasetURL`
- [x] 2. Remove any field that is no longer needed. For example, `update_announced` can be remove once all the code for the V1 API is removed.
- [x] 3. Rename some of the fields to make them more informative. For example, `info_ts` can be renamed to `last_update`.

Note: The fulfillment of this issue should be done after the removal of V1 API and support of SQLAlchemy in put in place.

**Comment by yarikoptic** [comment]
2 and 3 are pretty much outlined in the changes to the model needed to implement proper (cron or triggered) updates as in https://github.com/datalad/datalad-registry/issues/112#issuecomment-1610067233 . Either URL model gets renamed - I don't care much but indeed smth like `RepoUrl` (I think we deal only with datasets ATM but could be regular git repos without UUID I guess in the future) would be more appropriate but not critical to rename, but could be done in conjunction with other changes needing migration. So I will add it to the project along with that #112

**Comment by candleindark** [comment]
Yes, these changes will be done with whatever changes needed in #112.
