### ISSUE TITLE
Bug: The schemas of the response models are generated using aliases in the models as keys instead of property names in the models as keys

### ISSUE THREAD

**Issue by candleindark** [datalad/datalad-registry#191]
The schemas of response models are used in the auto-generated OpenAPI documentation of the API. These schemas of the response models are currently generated using aliases in the models as keys, and this way of generation is wrong for the API returns the models using the property names as the keys. Rectify the auto-generation of the OpenAPI documentation by having the schemas of the response models generated using the property names in the model as keys.

**Comment by candleindark** [comment]
Made an attempt to rectify the auto-generated OpenAPI documentation without success.

[A request](https://github.com/luolingchun/flask-openapi3/discussions/79#discussion-5303664) has been made to add a new feature in flask-openapi3 to support the desired OpenAPI documentation generation.

**Comment by yarikoptic** [comment]
FTR, `by_alias` from the request referenced above was implemented and released in https://github.com/luolingchun/flask-openapi3/blob/master/CHANGELOG.md#v250-2023-08-02
