### ISSUE TITLE
DLP: Dataset (identified by UUID) landing page - add ability to filter listing by UUID

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#212]
given a UUID, provide information about records for that UUID.  Could be as simple as making it possible to limit by a given UUID. ATM even search by UUID does not work: http://localhost:5000/overview/?filter=58b7fbd8-fbe0-11e7-bf1b-0cc47a6e9318 gives none.

**Comment by candleindark** [comment]
@yarikoptic I think we can close this one. We have been able to search by UUID for quite a while, through both the API `/api/v2/dataset-urls` endpoint and the web GUI.

**Comment by candleindark** [comment]
> given a UUID, provide information about records for that UUID. Could be as simple as making it possible to limit by a given UUID. ATM even search by UUID does not work: http://localhost:5000/overview/?filter=58b7fbd8-fbe0-11e7-bf1b-0cc47a6e9318 gives none.

BTW, currently to search for an exact match by `ds_id` through the web UI in the context of the above example is by accessing the following the URL, https://registry.datalad.org/overview/?query=ds_id%3A58b7fbd8-fbe0-11e7-bf1b-0cc47a6e9318.
