### ISSUE TITLE
Release datalad-registry 0.3.0

### ISSUE THREAD

**Issue by candleindark** [datalad/datalad-registry#216]
Release Datalad-registry as 0.3.0 by tagging it locally once #112 is complete.

**Comment by yarikoptic** [comment]
#112 was complete, please release

**Comment by candleindark** [comment]
How do I do it? Do I just tag a commit in master after #112?

**Comment by yarikoptic** [comment]
- `git tag -a 0.3.0` and enter brief description of the changes  since 0.2.0
- `git push origin 0.3.0`
- go to https://github.com/datalad/datalad-registry/releases/tag/0.3.0 and click there "Make release from the tag" and there "Save" or whatever that button is without any changes to it

**Comment by candleindark** [comment]
[0.3.0](https://github.com/datalad/datalad-registry/releases/tag/0.3.0) released.
