### ISSUE TITLE
FOI: what consumes/requires space in the image - minimize somehow?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#236]
ATM I see
```
❯ docker images
REPOSITORY                             TAG                            IMAGE ID       CREATED         SIZE
datalad-registry                       dev                            0fd3d4b208cf   8 days ago      1.14GB
datalad-registry                       debug                          3bff492fbced   8 days ago      1.14GB
```

so it is over a GB image. Sounds like too much ...

I have ran it and installed `ncdu` and `debian-goodies` to investigate. Here are the heaviest debian pkgs:

```
root@44d72652f233:/app# dpigs -n 20
73283 git-annex
51125 gcc-10
44132 guile-2.2-libs
35133 python3-pycryptodome
35084 git
33152 libicu67
27869 libperl5.32
27441 g++-10
25613 cpp-10
19944 libpython3.9-dev
17752 libstdc++-10-dev
17478 coreutils
17455 perl-modules-5.32
16014 locales
14502 libc6-dev
13897 binutils-common
13474 libgcc-10-dev
12833 libc6
9631 libasan6
8926 libtsan0

```

may be we could remove `-dev` and all the build tooling...

`ncdu` shows that lots coming from `/usr/local/lib/python3.9/dist-packages`

```
--- /usr/local/lib/python3.9/dist-packages -------------------------------------------------------------------------------------------------------
                         /..                                                                                                                      
   88.6 MiB [##########] /scipy
   60.7 MiB [######    ] /pandas
   37.8 MiB [####      ] /bids
   36.3 MiB [####      ] /numpy.libs
   35.5 MiB [####      ] /numpy
   34.2 MiB [###       ] /scipy.libs
   17.4 MiB [#         ] /sqlalchemy
   13.0 MiB [#         ] /pip
   11.3 MiB [#         ] /pydicom
   11.1 MiB [#         ] /nibabel
   10.1 MiB [#         ] /boto
    9.4 MiB [#         ] /pydantic
    8.1 MiB [          ] /datalad
..
```
here is what we have in `/usr`

```
--- /usr -----------------------------------------------------------------------------------------------------------------------------------------
                         /..
  451.3 MiB [##########] /local
  442.6 MiB [######### ] /lib
  201.4 MiB [####      ] /share                                                                                                                   
  143.9 MiB [###       ] /bin
   23.4 MiB [          ] /include
    4.2 MiB [          ] /sbin
   16.0 KiB [          ] /libexec
e   0.0   B [          ] /src
e   0.0   B [          ] /games
```

so just filing for our information (FOI) but not worth probably messing with it ATM

**Comment by candleindark** [comment]
> may be we could remove -dev and all the build tooling...

`-dev` is just the naming of the image. We didn't actually install any packages specified in `requirements_.txt` or `.[dev]` in this image. Can packaging the datalad-registry app in to a package help eliminating the need of installing those build tooling in the image?

We can also consider basing our image on one of [the official Python images](https://hub.docker.com/_/python).

**Comment by yarikoptic** [comment]
> > may be we could remove -dev and all the build tooling...
> 
> `-dev` is just the naming of the image.

I was talking about `-dev` debian packages like `libpython3.9-dev`

**Comment by candleindark** [comment]
> I was talking about -dev debian packages like libpython3.9-dev

**Comment by candleindark** [comment]
> I was talking about `-dev` debian packages like `libpython3.9-dev`

I just checked. Both `libpq-dev` and `python3-dev` are specifically required by `psycopg2`, the DB driver for Postgres.

I think we will have to find other ways to reduce the size of the image.

**Comment by yarikoptic** [comment]
most likely they are required only during installation so it could be built but then could be uninstalled...  E.g. if we were installing all components as already built and packaged in debian (e.g. python3-psycopg2 etc) and not with `pip install` - those -dev would not be needed and size would have been smaller.

But as I have mentioned -- that is more of an information for us, we aren't really at demand to reduce the size atm.  I just was surprised a little that it is that large.  Let's close for now
