### ISSUE TITLE
registry-submit takes awhile to complete

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#24]
ATM it seems that registering a new dataset triggers some action on the datalad-registry server (`clone`?) which holds up client (`registry-submit`) for an extended period of time. I did 

```shell
$> datalad -f '{path}' subdatasets -d ~/datalad -r --fulfilled on | while read ds; do datalad registry-submit -d "$ds" --sibling origin; done    
```
on a local instance of http://datasets.datalad.org installed locally with some random selection of subdatasets.

The command above held for long time after
```
registry-submit(ok): /home/yoh/datalad/allen-brain-observatory/visual-coding-neuropixels/raw-data (dataset) [Retrieved token]
```
before progressing to
```
registry-submit(ok): /home/yoh/datalad/allen-brain-observatory/visual-coding-neuropixels/raw-data (dataset) [Created token ref via push to origin]
```
server logs were 
```
web_1        | 172.27.0.1 - - [23/Mar/2021 20:27:35] "GET /v1/datasets/014dc7e0-07e3-11ea-860e-06a129876bb4/urls/aHR0cDSENSOREDdA==/token HTTP/1.1" 200 -
web_1        | 172.27.0.1 - - [23/Mar/2021 20:29:44] "POST /v1/datasets/014dc7e0-07e3-11ea-860e-06a129876bb4/urls HTTP/1.1" 202 -
```
so it was doing smth for over 2 minutes.  

I have not looked inside, but from "Created token ref via push to origin" I suspect that it might be actually pushing the entire repo to the registry, is that was is happening?  Or is it just that the server side does clone on the server side and that takes long?

In the former case: I do not think that there should be any pushing - client should just announce availability of a dataset from a url.  In the latter case: I think such server side operations should be allowed (I would even say that it should probably be a default behavior) to be staged to be done "out of band" and client (`registry-submit`) should just proceed forward without awaiting for some ultimate verdict either dataset was registered, while server would do whatever it needs to do to either register it or error out (if no dataset , or a different dataset found on that URL) somewhere in its logs.

**Comment by kyleam** [comment]
> so it was doing smth for over 2 minutes.

Thanks for the report.  Unfortunately I have don't any immediate ideas about what's going on.

> I have not looked inside, but from "Created token ref via push to origin" I suspect that it might be actually pushing the entire repo to the registry, is that was is happening?

No, the entire repo is not being pushed to the registry.  It's a `git push {token} {empty tree oid}:{token ref}` to the sibling.

> Or is it just that the server side does clone on the server side and that takes long?

No.  It's just the push above that's in between `GET .../token` and `POST .../urls`. `GET .../token` doesn't have a background task.  `POST .../urls` starts one task, but it shouldn't wait around for it.

**Comment by kyleam** [comment]
I'm still not sure what was going on here, but, with the rework in gh-29, I'm hoping it's resolved (especially if the underlying reason was gh-28).  Please reopen if you run into it again.
