### ISSUE TITLE
Q: anything to do to trigger populating "Commit	Annex keys	Last update"?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#26]
Still running the invocation of  #24 and now have "page 1 (13 URLs total)", but the right columns (Commit, Annex keys, Last update) are all empty.  Instance was started using `docker-compose up`.  In the terminal I see debug entries like
```
DEBUG in dataset_urls: Status for http://datasets.datalad.org/hcp-openaccess/HCP1200/100206/T1w/.git: unknown
```
Anything I should/could do to trigger some kind of action to get those values populated?

**Comment by yarikoptic** [comment]
woohoo -- I see those columns starting to be populated!  Is there any end point to query on the list/status of scheduled/ongoing jobs?  I do not see anything within `docs/openapi.yml`

**Comment by candleindark** [comment]
@yarikoptic Can we remove this issue or remake it into something else. I don't think it is relevant to the current version of Datalad registry.
