### ISSUE TITLE
Expose current search via API

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#269]
There is already interest (if not need) in using registry and its API (attn @ericearl and @remi-gau)
We have the `/api/v2/dataset-urls` endpoint which is kinda "too heavy" with already ways to limit the list of datasets.  But I guess could be loaded with one more exposing that basic search we have in the edit box.  That would also be useful for #163 . An alternative is to add `/api/v2/search` endpoint which would be similar to `/dataset-urls` one in return  but just limit based on search.

**Comment by candleindark** [comment]
@yarikoptic Just to be certain, the edit box you are referring to is the one indicated in the attached image, right?

![Screenshot 2023-11-17 at 12 40 27 PM](https://github.com/datalad/datalad-registry/assets/12135617/effe4326-8c47-414b-b0a7-01112e0e3f5a)

**Comment by yarikoptic** [comment]
yes

**Comment by candleindark** [comment]
@yarikoptic After a long discussion with ChatGPT, I think the best way to go is to add the search ability via a query parameter (let it be `search`) to the existing collection endpoint of `/api/v2/dataset-urls`, which already support some filtering of dataset URL functionality.

Here are a few benefits of doing so.

> Adding a search string as a query parameter to your existing collection endpoint for filtering does not violate any REST principles. In fact, it's a widely adopted and recommended practice for implementing search or complex filtering capabilities in RESTful APIs. This approach is aligned with REST's uniform interface constraint and leverages the query component of the URI to further refine the set of resources being requested.

> Combining Parameters: You can combine the search query parameter with other filtering parameters to allow users to perform a targeted search within a subset of your data. For example, a request might look like /api/v2/dataset-urls?category=science&search=climate, where category is an existing filter parameter and search is the new parameter you're adding for search functionality.

> Flexibility and Scalability: This approach is both flexible and scalable, allowing you to easily add more query parameters in the future for additional filtering and search capabilities. It also improves the user experience by providing a granular and powerful way to query data.

**Comment by yarikoptic** [comment]
I am ok with that.
We will then re-consider when we start indexing/search metadata at file level.
