### ISSUE TITLE
Automate (cron job script) getting updates from the datalad-usage-dashboard

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#271]
ATM (@candleindark correct me if I am wrong) the datasets we have known to registry came from a single "injection" of them into DB using https://github.com/datalad/datalad-registry/blob/master/tools/populate.py . 
That script seems to not care about "updates only mode".  So ideally, to not stress registry more than needed, we should not "post" on old URLs which it already knows.  

Thus likely we should add mode there to first

- get a list of already known URLs from registry
- POST only for new ones

and place that script on cron to run daily on the main server.

**Comment by candleindark** [comment]
@yarikoptic You are right. That script was initially written with the purpose to populate an empty Datalad-Registry.

Instead of placing that script on cron, can I implement the updates from datalad-usage-dashboard in our Celery scheduler within Datalad-Registry instead?

**Comment by yarikoptic** [comment]
Sure! I forgot that we have a formal schedule within the system
