### ISSUE TITLE
registry-submit should not reach out to siblings

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#28]
I  just spotted that my loop was stuck on
```
registry-submit(ok): /home/yoh/datalad/openfmri (dataset) [Retrieved token]
yoh@falkor.datalad.org's password: 
```

Might be related/reason for #24

I think `registry-submit` should just provide information about remote URLs as known locally, without doing anything else to first of all not leak possibly some sensitive information.  Actual access/discovery of relevant information beyond provided URL and (optionally, see #25) UUID should be done by datalad-registry server which would access only what is publicly accessible.

**Comment by kyleam** [comment]
As of gh-29, there's no interaction with the sibling.
