### ISSUE TITLE
Tune up main.css to look more like style in catalog and overall not that plain

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#290]
we have https://github.com/datalad/datalad-registry/blob/2d5e9e296b2edd71b99d36fee997ff64a131eb82/datalad_registry/static/main.css 

as we are hoping to (ab)use catalog, may be we should adopt its styling. But it seems to be more elaborate and uses bootstrap etc already.

@jsheunis WDYT -- is there any hope for an easy facelift of  http://registry.datalad.org/overview/ ? ;-)

**Comment by jsheunis** [comment]
I agree it's probably not a good idea to use the entirety of datalad-catalog's styling. Likely better to just update registry's existing CSS with a few new "facelifting" rules. I can take a shot at it when some time opens up.

**Comment by jsheunis** [comment]
@yarikoptic @candleindark is there a demo deployment of registry available somewhere, so that I can just inspect and edit css in the browser? would prevent having to set up everything via docker.

**Comment by candleindark** [comment]
@jsheunis Yes. There is a public instance at http://registry.datalad.org.

**Comment by yarikoptic** [comment]
and your local instance startup should be as simple as following https://github.com/datalad/datalad-registry?tab=readme-ov-file#to-develop -- if it is not, it is a bug. Which reminded me about #268 (ping @candleindark ) ;-)

**Comment by jsheunis** [comment]
Current progress (local):

<img width="1913" alt="Screenshot 2024-01-22 at 23 42 20" src="https://github.com/datalad/datalad-registry/assets/10141237/1559dc04-7569-4e92-ac40-7694256f8c28">

The logo was just a quick idea (same as catalog's) and doesn't have to be there.

Some more ideas:
- format columns containing sizes to include correct unit (kb, mb, etc)
- add tooltips when hovering over column headings that have been shortened
- shorten "datalad id" display with ellipses that can be hovered over to display full id
- display "last updated" datetime in a user friendly format (also shortened)

**Comment by candleindark** [comment]
> Current progress (local):
> 
> <img alt="Screenshot 2024-01-22 at 23 42 20" width="1913" src="https://private-user-images.githubusercontent.com/10141237/298749490-1559dc04-7569-4e92-ac40-7694256f8c28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjQ3OTUsIm5iZiI6MTcwNTk2NDQ5NSwicGF0aCI6Ii8xMDE0MTIzNy8yOTg3NDk0OTAtMTU1OWRjMDQtNzU2OS00ZTkyLWFjNDAtNzY5NDI1NmY4YzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDIzMDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZGY2YzFiOGJmZWNkMDZjYmE1YzI0YzIxZmEzMGZmODQ0MGUyZGE3Mzg2NWE5ZWJiNzIwMDMyOTFkMWY3MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jeZUerqffxOjv8WVUsLk2_9Y1AFFkEzHGNh7Z3sVPoQ">
> The logo was just a quick idea (same as catalog's) and doesn't have to be there.
> 
This look great already, and the style is consistent with other Datalad project.

> Some more ideas:
> 
> * format columns containing sizes to include correct unit (kb, mb, etc)
> * add tooltips when hovering over column headings that have been shortened
> * shorten "datalad id" display with ellipses that can be hovered over to display full id
> * display "last updated" datetime in a user friendly format (also shortened)

These are all great ideas. Can you implement them in the frontend, or do you need any modification in the backend to support these changes?

**Comment by yarikoptic** [comment]
@jsheunis thank you!   Re size column -- note that we have sorting capability for it, so underlying value cannot be just humanized version.  Is there a CSS way to do rendering conversion? Similarly is it possible in CSS/JS shorten that long DS UUID?

Note that in the longer run I think we should redo this table in something like https://datatables.net/, a prehistoric version of which I believe I use for https://datasets.datalad.org .

**Comment by jsheunis** [comment]
I was trying to find a way to use pure CSS/JS combo to render the values differently without changing the html itself, but haven't been able to. But i think it's possible using the CSS `:after`/`:before` selectors and the `content` property. I will try this out. The alternative is to use a framework like Vue, which can then take over the sorting / paging / rendering capabilities. What's your feeling about that?

Re: 

> Can you implement them in the frontend, or do you need any modification in the backend to support these changes?

I think ideally all should be implemented in the frontend.

**Comment by yarikoptic** [comment]
> I was trying to find a way to use pure CSS/JS combo to render the values differently without changing the html itself, but haven't been able to. But i think it's possible using the CSS `:after`/`:before` selectors and the `content` property. I will try this out. The alternative is to use a framework like Vue, which can then take over the sorting / paging / rendering capabilities. What's your feeling about that?

I would say: THANK YOU very much for trying, but I think it would better not to dwell on those particular aspects too much at this point. Best would be to merge this initial face lift and then may be look at particular aspects or even just work to migrate to those datatables and see what it could do for us in terms of visualization/styling

**Comment by candleindark** [comment]
> > Can you implement them in the frontend, or do you need any modification in the backend to support these changes?
> 
> I think ideally all should be implemented in the frontend.

The current `/overview` path is based on some legacy code. We want to eventually rebuild a new frontend based on the [API](http://registry.datalad.org/openapi/swagger). I think it is a good idea to keep what you have now, as @yarikoptic suggested, and move on for now if those changes you suggested require much more efforts.
