### ISSUE TITLE
Switch to use postgresql

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#36]
To provide solution for #34 and to enable parallel operations we should switch to use some "proper" DBM rather than sqlite. I think we need

- [ ] extend/generalize `docker-compose.broker.yml` to provide also a postgresql DB.  If somehow actual DB could also reside under `instance/` -- would be great, if not -- could live in docker's volume. Not sure yet what to do about "all-in-one" docker-compose.yml... may be there is a way to have a singular docker-compose recipe with some parametrization to start either full instance or just broker + DB?
- [ ] add fixture to tests, similar to the one in dandi-cli, to use that dockerized instance instead of sqlite

**Comment by jwodder** [comment]
@yarikoptic Is #34 actually causing any problems during testing or just in production?  I think it'd be simpler to continue to use SQLite for testing and only use PostgreSQL when deploying.

**Comment by yarikoptic** [comment]
I ran into it in production IIRC, so ATM it might indeed not be needed for testing setup. BUT I expect code to go through RFing so it would not be as sequential in how it does the celery jobs (https://github.com/datalad/datalad-registry/issues/38).   And for that it would need to allow concurrent operations anyways, so I thought that switching to just use postgresql all the time would be better and provide more consistent setup between testing and production.

**Comment by jwodder** [comment]
@yarikoptic 

* When using PostgreSQL for testing, should the data volume still be stored under `instance/`?
* Do you have any preference for how the database password should be managed?

**Comment by yarikoptic** [comment]
> * When using PostgreSQL for testing, should the data volume still be stored under `instance/`?

I would assume that a test suite run would have its own `instance/` (similar to production), so if possible to store there -- would be great

> * Do you have any preference for how the database password should be managed?

no preferences ATM, may be some env var?

**Comment by jwodder** [comment]
@yarikoptic 

> I would assume that a test suite run would have its own instance/ (similar to production), so if possible to store there -- would be great

Why exactly do you want to do that?  The test database would need to be reset on each test run, and the easiest way to do that would be to not mount it at all.

**Comment by yarikoptic** [comment]
sorry, I wasn't clear -- I meant that test suite would use some tmpdir for `instance/` so it would not persist across reruns, but would still have DB under that tmpdir which would get destroyed after.
