### ISSUE TITLE
add size of .git/objects to the schema/display

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#40]
even though it is subject to fluctuate depending on local repacking/gc, I think it would be useful to gather/display that information since would be reflective of space etc needed for an initial clone of that repository

**Comment by jwodder** [comment]
@yarikoptic Is using `ds.repo.count_objects` the correct way to get the size, or should I do something else?

**Comment by yarikoptic** [comment]
sure.  I guess we would need `size + size-pack`, but greedy me now wonders if we should just store a complete json record for it, WDYT?

**Comment by jwodder** [comment]
@yarikoptic Using just the size would be easier to store & display, and I don't really see the need to expose the extra information.

**Comment by yarikoptic** [comment]
ok, let's proceed with just total `size`
