### ISSUE TITLE
Handle datasets submitted via `/urls/{url_encoded}` and `/datasets/{uuid}/urls/{url_encoded}` one after the other

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad-registry#48]
(This is a to-do item for later; I'm not going to try to fix this at the moment.)

As of commit 4fc0275, if a dataset is submitted via `/urls/{url_encoded}` (which causes a row with a null `ds_id` to be added to the database) and then, before the celery task completes, submitted again via `/datasets/{uuid}/urls/{url_encoded}`, then the latter endpoint will query the database for the given UUID and URL, find nothing (because the UUID in the row isn't set), and then try to add a row with the same URL to the database, leading to an error.

**Comment by yarikoptic** [comment]
Thank you @jwodder for the issue. Would you be so kind to address it? (we are PR free ATM here, so would be good time now I guess)

**Comment by jwodder** [comment]
@yarikoptic 
* [There is an outstanding PR](https://github.com/datalad/datalad-registry/pull/50); please merge it in order to avoid merge conflicts later.
* What behavior change do you recommend for solving this issue?
