### ISSUE TITLE
Tests started to stall

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#65]
As could be seen from https://github.com/datalad/datalad-registry/actions/workflows/test.yml and I forgot any detail I discovered on where they stall when I quickly tried to figure it out.  But since didn't happen before it is something about dependencies I guess. @jwodder please try to figure it out

**Comment by jwodder** [comment]
@yarikoptic The stalls appear to be due to an incompatibility with Flask-SQLAlchemy 3.0 (released on October 4); restricting it to a lower version gets rid of the stall.  I have yet to determine the exact change that we need to make to update our code.
