### ISSUE TITLE
extend basic metadata extracted from annex with "total" info about worktree

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#69]
ATM (https://github.com/datalad/datalad-registry/blob/master/datalad_registry/tasks.py#L88)  we run only `annex info origin` to get information about how much that particular origin has. Would be useful to know about number and size of the annexed files in the worktree:

```
❯ git annex info --json --bytes | jq . | grep work
  "size of annexed files in working tree": "2415778654",
  "annexed files in working tree": 80,
```

**Comment by candleindark** [comment]
This request is now fulfilled by https://github.com/datalad/datalad-registry/pull/75.
