### ISSUE TITLE
Run via rootless podman or singularity/apptainer?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#89]
We should check with @asmacdo if that would be possible to avoid possible "kill all by using docker" scenario ;)

**Comment by asmacdo** [comment]
huh?

**Comment by asmacdo** [comment]
Without fully understanding the use case I think the answer is yes.

With podman, we have 4 options.
- run podman as root, run container as root
- run podman as root, run container as non-root (specify -u someuser)
- run podman as non-root, run the container as root (ex. UID 0 inside the container maps to UID 1000)
- run podman as non-root, run the container as non-root. safety first!

**Comment by yarikoptic** [comment]
FWIW we have `podman` installed on smaug now.
In development mode we need to start `db` and `broker` from https://github.com/datalad/datalad-registry/blob/master/docker-compose.yml . 
https://github.com/datalad/datalad-registry/blob/master/up is the script used for that purpose. 

Can you @asmacdo work with @candleindark and research into possibility of the "non-root" execution of those instances?  I think it should be feasible since really there is no need for "outside root" - ports they use are not privileged so for that root also would not be needed.

**Comment by candleindark** [comment]
@yarikoptic Podman on Smaug is currently @ 3.0.1. Can we have it updated to the current version 4.4.1?

**Comment by yarikoptic** [comment]
I've tried to backport 4.3.1 (present in debian unstable) but "no good".

Why would we need 4.4.1?  is there a way for user-space installation (attn @asmacdo)?

**Comment by asmacdo** [comment]
Seems like it's **possible** but probably not worth the effort.

https://github.com/containers/podman/issues/3100

**Comment by candleindark** [comment]
> I've tried to backport 4.3.1 (present in debian unstable) but "no good".
> 
> Why would we need 4.4.1? is there a way for user-space installation (attn @asmacdo)?

All the documentation I have been reading is at version 4+. I was just wondering if we can upgrade to version 4+ just for consistency. It actually don't have to be 4.4.1 in particular.

**Comment by candleindark** [comment]
Datalad-registry has been run by Podman for more than 7 days. I think we should close this issue.

**Comment by yarikoptic** [comment]
feel welcome to close issues you consider addressed. Where possible/relevant -- reference a commit or PR which closed it.  In this case I guess it might benefit from a quick section in README.md on podman and settings to use to avoid containers being killed.

**Comment by candleindark** [comment]
Note:
Before closing this issue, provide a section on README.md for running registry on Podman. This section should provide the solution to avoid Podman containers being killed by systemd.

**Comment by yarikoptic** [comment]
could we consider #102 as a replacement for this one? ;)

**Comment by candleindark** [comment]
Sure, let's close this one.
